# _config.yml
remote_theme: "mmistakes/minimal-mistakes"
title: "iampsr"
description: "iampsr â€” motorcycle rides, gear, and videos"
baseurl: ""          # leave blank for user.github.io sites
url: "https://iampsr.com"

plugins:
  - jekyll-feed

# recommended minimal mistakes options (you can expand later)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
